---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: template_sever_name
  namespace: template_namespace_name
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
spec:
  rules:
    - host: template_sever_name.template_namespace_name.template_ingress_domain_prefix
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: template_sever_name
                port:
                  number: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: template_sever_name
    jmx-type: service-jvm
  name: template_sever_name
  namespace: template_namespace_name
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: metrics
      port: 12345
      targetPort: 12345
  selector:
    app: template_sever_name
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: template_sever_name
  namespace: template_namespace_name
spec:
  replicas: template_rc_init_count
  selector:
    matchLabels:
      app: template_sever_name
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: template_sever_name
    spec:
      nodeSelector:
        "shilintan.io/service-type-service-java": "v"
      containers:
        - name: app
          image: template_sever_image
          imagePullPolicy: IfNotPresent
          env:
            - name: TZ
              value: Asia/Shanghai
            - name: JAVA_OPTS
              valueFrom:
                configMapKeyRef:
                  key: JAVA_OPTS
                  name: template_sever_name-rc
            - name: SPRING_PROFILES
              valueFrom:
                configMapKeyRef:
                  name: common-env-java
                  key: SPRING_PROFILES
          ports:
            - containerPort: 80
              name: http
            - containerPort: 12345
              name: metrics
          stdin: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          tty: true
          resources:
            requests:
              cpu: template_app_resources_requests_cpu
              memory: template_app_resources_requests_memory
              ephemeral-storage: template_app_resources_requests_ephemeral_storage
            limits:
              cpu: template_app_resources_limits_cpu
              memory: template_app_resources_limits_memory
              ephemeral-storage: template_app_resources_limits_ephemeral_storage
          livenessProbe:
            failureThreshold: 300
            httpGet:
              path: /actuator
              port: 80
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 3
          readinessProbe:
            failureThreshold: 20
            httpGet:
              path: /actuator
              port: 80
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 3
          volumeMounts:
            - mountPath: /app/config-file
              name: config-common-file
            - mountPath: /app/config
              name: service-config
            - mountPath: /app/env
              name: common-env-config
            - mountPath: /app/logs
              name: logs-dir
        - name: promtail
          args:
            - -config.file=/etc/promtail/config.yaml
            - -config.expand-env=true
          image: grafana/promtail:2.8.3-amd64
          imagePullPolicy: IfNotPresent
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: SERVICENAME
              value: template_sever_name
          resources:
            requests:
              cpu: 10m
              memory: 100Mi
              ephemeral-storage: 1Gi
            limits:
              cpu: 1000m
              memory: 1Gi
              ephemeral-storage: 1Gi
          volumeMounts:
            - mountPath: /mnt
              name: logs-dir
            - mountPath: /etc/promtail/config.yaml
              name: logging-loki-promtail-service-log
              readOnly: true
              subPath: config.yaml
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      dnsPolicy: ClusterFirst
      terminationGracePeriodSeconds: 100
      imagePullSecrets:
        - name: regcred
      volumes:
        - name: common-env-config
          configMap:
            name: common-env-java
        - name: config-common-file
          configMap:
            name: common-file-java
        - name: service-config
          configMap:
            name: template_sever_name-config
        - emptyDir: {}
          name: logs-dir
        - configMap:
            name: logging-loki-promtail-service-log
          name: logging-loki-promtail-service-log