apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: rabbitmq
    meta.helm.sh/release-namespace: test
  labels:
    app.kubernetes.io/instance: rabbitmq
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: rabbitmq
    helm.sh/chart: rabbitmq-12.0.9
  name: rabbitmq-out
  namespace: test
spec:
  ports:
    - name: amqp
      port: 5672
      protocol: TCP
      targetPort: amqp
      nodePort: 31601
    - name: epmd
      port: 4369
      protocol: TCP
      targetPort: epmd
    - name: dist
      port: 25672
      protocol: TCP
      targetPort: dist
    - name: http-stats
      port: 15672
      protocol: TCP
      targetPort: stats
      nodePort: 31309
  selector:
    app.kubernetes.io/instance: rabbitmq
    app.kubernetes.io/name: rabbitmq
  sessionAffinity: None
  type: LoadBalancer