---
# 外部网络
apiVersion: v1
kind: Service
metadata:
  name: gitlab-out
  namespace: env
spec:
  selector:
    app: gitlab
  ports:
    - name: for-80
      port: 80
      targetPort: 80
      nodePort: 32529
    - name: for-443
      port: 443
      targetPort: 443
    - name: for-22
      port: 22
      targetPort: 22
  type: LoadBalancer