apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: mongodb
    meta.helm.sh/release-namespace: test
  labels:
    app.kubernetes.io/component: mongodb
    app.kubernetes.io/instance: mongodb
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: mongodb
    helm.sh/chart: mongodb-13.16.1
  name: mongodb-out
  namespace: test
spec:
  ports:
    - name: mongodb
      port: 27017
      protocol: TCP
      targetPort: mongodb
  selector:
    app.kubernetes.io/component: mongodb
    app.kubernetes.io/instance: mongodb
    app.kubernetes.io/name: mongodb
  sessionAffinity: None
  type: LoadBalancer
