---
# loki
apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-promtail-gateway-nginx
  namespace: nginx
data:
  config.yaml: |
    server:
      disable: true
    positions:
      filename: /promtail-positions.yaml
    clients:
      - url: http://10.96.2.189/loki/api/v1/push
    scrape_configs:
      - job_name: logging-loki-promtail-gateway-nginx-log
        static_configs:
          - targets:
              - localhost
            labels:
              scrape_job: gateway-nginx
              __path__: /mnt/**/*.log
              namespace: ${NAMESPACE}
              app: ${SERVICENAME}
              pod: ${HOSTNAME}