---
# Source: mongodb/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: release-name-mongodb
  namespace: default
  labels:
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: mongodb
    helm.sh/chart: mongodb-13.17.0
    app.kubernetes.io/component: mongodb
type: Opaque
data:
  mongodb-root-password: "b2JuVTR5WkZmWXZDeEFuTVZkRjg="
  mongodb-replica-set-key: "RXV4VVdQWlJRMw=="
