---
# Source: rabbitmq/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: release-name-rabbitmq
  namespace: "default"
  labels:
    app.kubernetes.io/name: rabbitmq
    helm.sh/chart: rabbitmq-12.0.9
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
type: Opaque
data:
  rabbitmq-password: "b2JuVTR5WkZmWXZDeEFuTVZkRjg="
  rabbitmq-erlang-cookie: "VzhuRDZWR29BNFlxMlhKekdnYVFnTDJtcWpHdXpkZEI="
