---
# Source: rabbitmq/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: release-name-rabbitmq
  namespace: "test"
  labels:
    app.kubernetes.io/name: rabbitmq
    helm.sh/chart: rabbitmq-12.0.9
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
type: Opaque
data:
  rabbitmq-password: "d2VuZGk2NjZf"
  rabbitmq-erlang-cookie: "ems2TlRhU3BvajdUYXlpOFBmSUdSdW5nZkJPNjR4a3o="
